tarefas/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('lista-categorias/', views.list_category, name='list_category'),
    path('nova-categoria/', views.new_category, name='new_category'),
    path('nova-tarefa/', views.new_task, name='new_task'),
    path('deleta-tarefa/<int:id>', views.delete_task, name='delete_task'),
    path('atualizar-tarefa/<int:id>', views.update_task, name='update_task'),
    path('deleta-categoria/<int:id>', views.delete_category, name='delete_category'),
    path('atualizar-cagegoria/<int:id>', views.update_category, name='update_category'),
    path('detalhe-tarefa/<int:id>', views.task_details, name='task_details'),
    path('buscar/', views.search, name='search'),
]

todo/urls.py
from django.contrib import admin
from django.urls import include, path

from tarefas import urls as tarefas_urls
from accounts import urls as accounts_urls

from core import views

urlpatterns = [
    path('tarefas/', include(tarefas_urls)),
    path('accounts/', include(accounts_urls)),
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
]

tarefas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class TarefaManager(models.Manager):
    def search(self, query, user):
        return self.get_queryset().filter(models.Q(nome__icontains=query) | 
                                    models.Q(descricao__icontains=query) | 
                                    models.Q(categoria__nome__icontains=query), 
                                    user=user)

class Categoria(models.Model):
    nome = models.CharField(max_length=100, verbose_name='Nome')
    descricao = models.TextField(verbose_name='Descrição')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    

    def __str__(self):
        return self.nome


class Tarefa(models.Model):
    PRIORIDADE_CHOICES = (
        ('B', 'Baixa'),
        ('M', 'Média'),
        ('A', 'Alta'),
    )
    
    CONCLUIDO = 'C'
    CANCELADO = 'CD'
    STATUS_CHOICES = (
        (CONCLUIDO, 'Concluído'),
        (CANCELADO, 'Cancelado'),

    )
    nome = models.CharField(max_length=100, verbose_name='Nome')
    descricao = models.TextField(blank=True, verbose_name='Descrição')
    data_final = models.DateField(verbose_name='Data final')
    prioridade = models.CharField(max_length=1, choices=PRIORIDADE_CHOICES, verbose_name='Prioridade')
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, verbose_name='Categoria')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(u'Status', max_length=5, choices=STATUS_CHOICES, blank=True, default='')

    objects = TarefaManager()

    def __str__(self):
        return self.nome

tarefas/forms.py
from django import forms

from .models import Categoria, Tarefa


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        exclude = ('user',)


class TarefaForm(forms.ModelForm):
    class Meta:
        model = Tarefa
        exclude = ('user',)

    def __init__(self, user=None, *args, **kwargs):
        super(TarefaForm, self).__init__(*args, **kwargs)
        if user is not None:
            self.fields['categoria'].queryset = Categoria.objects.filter(user=user)

tarefas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import CategoriaForm, TarefaForm
from .models import Categoria, Tarefa


# Create your views here.
@login_required
def new_category(request):
    if request.method == 'POST':
        form = CategoriaForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.user = request.user
            f.save()
            return redirect('list_category')
        else:
            print(form.errors)
    else:
        form = CategoriaForm()
    return render(request, 'tarefas/new_category.html', {'form': form})

@login_required
def list_category(request):
    categories = Categoria.objects.filter(user=request.user)
    return render(request, 'tarefas/list_categories.html', {'categories': categories})

@login_required
def new_task(request):
    categoria = Categoria.objects.filter(user=request.user)
    if not categoria:
        messages.error(request, 'Você precisa criar uma categoria primeiro!')
        return render(request, 'tarefas/list_categories.html')
    elif request.method == 'POST':
        form = TarefaForm(user=request.user, data=request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.user = request.user
            f.save()
            return redirect('home')
        else:
            form.errors
    else:
        form = TarefaForm(user=request.user)
    return render(request, 'tarefas/new_task.html', {'form': form})

@login_required
def delete_task(request, id):
    task = Tarefa.objects.get(id=id)
    if task.user == request.user:
        task.delete()
    else:
        messages.error(request, 'Você não tem permissão para exlcuir essa tarefa.')
        return render(request, 'home/index.html')
    return redirect('home')

@login_required
def update_task(request, id):
    task = get_object_or_404(Tarefa, id=id, user=request.user)
    if request.method == 'POST':
        form = TarefaForm(user=request.user, data=request.POST, instance=task)
        if form.is_valid():
            form.save()    
            return redirect('home')
    else:
        form = TarefaForm(user=request.user, instance=task)
    return render(request, 'tarefas/new_task.html', {'form':form})

@login_required
def delete_category(request, id):
    categorie = Categoria.objects.get(id=id)
    if categorie.user == request.user:
        categorie.delete()
    else:
        messages.error(request, 'Você não tem permissão para exlcuir essa categoria.')
        return render(request, 'tarefas/list_categories.html')        
    return redirect('list_category')

@login_required
def update_category(request, id):
    category = get_object_or_404(Categoria, id=id, user=request.user)
    if request.method == 'POST':
        form = CategoriaForm(request.POST, instance=category)
        if form.is_valid():
            form.save()    
            return redirect('list_category')
    else:
        form = CategoriaForm(instance=category)
    return render(request, 'tarefas/new_category.html', {'form':form})


@login_required
def search(request):
    query = request.GET.get('search')
    if query is not None:
        result = Tarefa.objects.search(query, request.user)
    return render(request, 'tarefas/search_result.html', {'result':result})


@login_required
def task_details(request, id):
    task = get_object_or_404(Tarefa, id=id)
    return render(request, 'tarefas/result_details.html', {'task':task})

tarefas/templates/tarefas/list_categories.html
{% extends "base.html" %}

{% block container %}
<h1>Lista de Categorias</h1>
    {% if messages %}
        {% for message in messages  %}
        <div class="alert alert-danger">
          {{message }}
        </div>
        {% endfor %}
    {% endif %}
    
    {% if categories %}
    
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Categoria</th>
                <th>Descrição</th>
                <th colspan="2" style="text-align:center">Açães</th>
            </tr>
        </thead>
        <tbody>
            {% for c in categories %}
              <tr>
                  <td>{{ c.nome }}</td>
                  <td>{{ c.descricao }}</td>
                  <td class="text-center"><a href="{% url 'update_category' c.id %}" class="btn btn-info btn-xs">Editar</a></td>
                  <td class="text-center"><a href="{% url 'delete_category' c.id %}" class="btn btn-info btn-xs">Excluir</a></td>
        
              </tr>
            {% endfor %}
        </tbody>
    </table>    
    {% else %}
    <div class="alert alert-warning"></div>
    {% endif %}
    <a href="{% url 'new_category'%}" class="btn btn-primary">Adicionar Categoria</a>
{% endblock container %}

tarefas/templates/tarefas/new_category.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block container %}
<h1 class="text-center">Nova Categoria</h1>
<div class="col-md-6 col-md-offset-3">
    {% if errors %}
    <div class="alert alert-danger">
      {% for error in errors  %}
        {{ error }}
      {% endfor %}
    </div>
    {% endif %}
<form class="" action="" method="post">
    {% csrf_token %}
	<div class="form-group">
        <label for="{{ form.name.id_for_label }}">Nome</label>
        {{ form.nome|add_class:"form-control" }}
    </div>
	<div class="form-group">
        <label for="{{ form.descricao.id_for_label }}">Descrição</label>
        {{ form.descricao|add_class:"form-control" }}
    </div>
    <div class="form-group text-center">
        <button class="btn btn-primary" type="submit">Salvar</button>
    </div>
</form>
</div>
{% endblock container %}

tarefas/templates/tarefas/new_task.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block container %}
<h1 class="text-center">Tarefa</h1>
<div class="col-md-6 col-md-offset-3">
<form class="" action="" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="{{ form.nome.id_for_label }}">Nome</label>
        {{ form.nome|add_class:"form-control" }}
    </div>
    <div class="form-group">
        <label for="{{ form.descricao.id_for_label }}">Descrição</label>
        {{ form.descricao|add_class:"form-control"|attr:"rows:5" }}
    </div>
    <div class="form-group">
        <label for="{{ form.data_final.id_for_label }}">Data Final</label>
        {{ form.data_final|add_class:"form-control"|attr:"placeholder:Ex 06/06/2018" }}
    </div>
    <div class="form-group">
        <label for="{{ form.prioridade.id_for_label }}">Prioridade</label>
        {{ form.prioridade|add_class:"form-control" }}
    </div>
    <div class="form-group">
        <label for="{{ form.categoria.id_for_label }}">Categoria</label>
        {{ form.categoria|add_class:"form-control" }}
    </div>
    {% if form.instance.id %}
    <div class="form-group">
        <label for="{{ form.status.id_for_label }}">Status</label>
        {{ form.status|add_class:"form-control" }}
    </div>
    {% endif %}
    <div class="form-group text-center">
        <button type="submit" class="btn btn-primary text-center">Salvar</button>
    </div>
</form>
</div>
{%  endblock container %}

tarefas/templates/tarefas/result_details.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block container %}
<h1 >Detalhes da Tarefa</h1>

<form class="" action="" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="">Nome:</label>
        {{ task.nome }}
    </div>
    <div class="form-group">
        <label for="">Descrição:</label>
        {{ task.descricao }}
    </div>
    <div class="form-group">
        <label for="">Data Final:</label>
        {{ task.data_final }}
    </div>
    <div class="form-group">
        <label for="">Prioridade:</label>
        {{ task.get_prioridade_display }}
    </div>
    <div class="form-group">
        <label for="">Categoria:</label>
        {{ task.categoria }}
    </div> 
</form>

{%  endblock container %}

tarefas/templates/tarefas/search_result.html
{% extends "base.html" %}

{% block container %}
<h1>Resultado da busca:</h1>
{% if result %}
  {% for r in result %}
    <a href="{% url 'task_details' r.id %}"><h3>{{ r.nome }}</h3></a>
  {% endfor %}
{% else %}
    <div class="alert alert-warning"><p>Nenhum resultado encontrado!</p></div>
{% endif %}
{% endblock container %}